kind: service
apiVersion: v1
metadata:
  name: directsite
  labels:
    app: directsite
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
 selector:
  app: dircetsite
type: LoadBalancer
